# Generated by Django 6.0.4 on 2026-04-22 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("duration_minutes", models.IntegerField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Comedy", "Comedy"),
                            ("Drama", "Drama"),
                            ("Horror", "Horror"),
                            ("Sci-Fi", "Sci-Fi"),
                            ("Romance", "Romance"),
                            ("Thriller", "Thriller"),
                            ("Animation", "Animation"),
                        ],
                        max_length=100,
                    ),
                ),
                ("release_date", models.DateField()),
                ("poster_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Showtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_date", models.DateField()),
                ("show_time", models.TimeField()),
                ("total_seats", models.IntegerField(default=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showtimes",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "unique_together": {("movie", "show_date", "show_time")},
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=5)),
                ("is_booked", models.BooleanField(default=False)),
                ("booked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "showtime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="movies.showtime",
                    ),
                ),
            ],
            options={
                "unique_together": {("showtime", "seat_number")},
            },
        ),
    ]
