# Generated by Django 6.0.4 on 2026-04-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_movie_poster_movie_poster_url'),
    ]

    operations = [
    ]
